### ISSUE TITLE
SwiftWebSocket dependency has wrong version tag in Cartfile

### ISSUE THREAD

**Issue by eelcokoelewijn-afrogleap** [siegesmund/SwiftDDP#27]
Hi, 

When i run carthage update i get the following error:
_Failed to check out repository into /dependencies/SwiftWebSocket: No object named "v2.6.0" exists_

Could you update the tag to "2.6.0" instead of "v2.6.0"?

Thanks.

**Comment by siegesmund** [comment]
Done.

**Comment by eelcokoelewijn-afrogleap** [comment]
@siegesmund Thanks for updating the Cartfile dependency for SwiftWebSocket. But it still seems to checkout the v2.6.0 tag instead of the 2.6.0 tag.
File now seems to be missing...

**Comment by eelcokoelewijn-afrogleap** [comment]
@siegesmund Thanks for the update on removing the Cartfile. Which dependencies aren't building reliably with swift 2.2?

**Comment by siegesmund** [comment]
It's Quick and Nimble, used for tests of the DDP functionality. I've commented them out and added the Cartfile back. It should build now.

**Comment by eelcokoelewijn-afrogleap** [comment]
Thanks for putting the Cartfile back, when i run the `carthage update` command i'm still getting: _org.carthage.CarthageKit/dependencies/SwiftWebSocket: No object named "v2.6.0" exists_ Error.

Any ideas? 

Using latest version of carthage 0.15.2 and also removed the CarthageKit/dependencies

**Comment by siegesmund** [comment]
Have you cloned the repo? Or are you trying to install SwiftDDP with Carthage? I haven't pushed a new version, so you'll need to install @ the latest commit, not the most recent version.

**Comment by iain17** [comment]
@eelcokoelewijn-afrogleap Try clearing the local checkout and run carthage update again

**Comment by eelcokoelewijn-afrogleap** [comment]
That would explain it. No cloning, i will try to use the latest commit.
